//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nmap_query.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("nmap_query.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;?xml-stylesheet href=&quot;file:///C:/Program Files/Nmap/nmap.xsl&quot; type=&quot;text/xsl&quot;?&gt;
        ///&lt;!-- Nmap 6.40 scan initiated Sun Jan 05 03:54:16 2014 as: &amp;quot;C:\\Program Files\\Nmap\\nmap.exe&amp;quot; -oX - -&amp;#45;open -sT 10.0.2.0/24 --&gt;
        ///&lt;nmaprun scanner=&quot;nmap&quot; args=&quot;&amp;quot;C:\\Program Files\\Nmap\\nmap.exe&amp;quot; -oX - -&amp;#45;open -sT 10.0.2.0/24&quot; start=&quot;1388922856&quot; startstr=&quot;Sun Jan 05 03:54:16 2014&quot; version=&quot;6.40&quot; xmloutputversion=&quot;1.04&quot;&gt;
        ///&lt;scaninfo type=&quot;connect&quot; protocol=&quot;tcp&quot; numservices=&quot;1000&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string nmap_results {
            get {
                return ResourceManager.GetString("nmap_results", resourceCulture);
            }
        }
    }
}
